### ISSUE TITLE
ERRO: conda env create -n scgpt --file scgpt_bench.yml

### ISSUE THREAD

**Issue by noob000007** [HelloWorldLTY/scEval#7] opened 2024-08-23 04:56 UTC
$ conda env create -n scgpt --file scgpt_bench.yml
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done
...
...
Collecting chex==0.1.7 (from -r /home/yhxiao/xiaoyihang/scEval/condaenv.sq43t7uy.requirements.txt (line 27))
  Downloading chex-0.1.7-py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.6/89.6 kB 617.2 kB/s eta 0:00:00
Collecting claude-api==1.0.17 (from -r /home/yhxiao/xiaoyihang/scEval/condaenv.sq43t7uy.requirements.txt (line 28))
  Downloading claude_api-1.0.17-py3-none-any.whl (6.2 kB)
Collecting click==8.1.3 (from -r /home/yhxiao/xiaoyihang/scEval/condaenv.sq43t7uy.requirements.txt (line 29))
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 679.0 kB/s eta 0:00:00

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.1.8 Requires-Python >=3.9; 0.1.81 Requires-Python >=3.9; 0.1.82 Requires-Python >=3.9; 0.1.83 Requires-Python >=3.9; 0.1.84 Requires-Python >=3.9; 0.1.85 Requires-Python >=3.9; 0.1.86 Requires-Python >=3.9; 0.10.0 Requires-Python >=3.9; 0.10.0rc1 Requires-Python >=3.9; 0.10.1 Requires-Python >=3.9; 0.10.2 Requires-Python >=3.9; 0.10.3 Requires-Python >=3.9; 0.10.4 Requires-Python >=3.9; 0.10.5 Requires-Python >=3.9; 0.10.5.post1 Requires-Python >=3.9; 0.10.6 Requires-Python >=3.9; 0.10.7 Requires-Python >=3.9; 0.10.8 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement cmap2d==0.0.1.dev0 (from versions: none)
ERROR: No matching distribution found for cmap2d==0.0.1.dev0

failed

CondaEnvException: Pip failed

**Comment by HelloWorldLTY** [comment] 2024-08-23 05:01
Hi, thanks for your interests of our work. I think you can directly delete the cmap2d instruction and try again. I refer from DestVI (https://github.com/romain-lopez/DestVI-reproducibility/blob/master/requirements.txt) and it might be outdated now.

**Comment by noob000007** [comment] 2024-08-23 06:30
The `scEval/installation_baselines/` folder contains `scbert`, `scgpt`, and `tgpt.yml` files, which cannot be installed directly with Conda due to various dependency conflicts or other errors. There may also be issues with other files that have not yet been tested. The issues with `scgpt_bench.yml` were not fully resolved yet. 

Your work is very meaningful, and I look forward to your updates. It would be greatly appreciated if you could reproduce and upload the correct `.yml` files. Thank you very much.

**Comment by HelloWorldLTY** [comment] 2024-08-23 16:44
```
The issues with scgpt_bench.yml were not fully resolved yet.
```

Could you please provide more details about it? I test it in our environment, although installing of pyg, destvi, etc cannot work, evaluation actually does not require these files (but need to reproduce our work or use knowledge graph augmen for scGPT). I have updated a version which should be able to install in your system after testing it, feel free to try it.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/89d1049a-7cb0-4a78-b927-5a05524b0bac">


Also, are you only facing problems in installing scbert, scgpt and tgpt? You could refer my new installation instruction to improve it, and it will be great if you can create a pull request with corrected yml file. Thanks.

**Comment by HelloWorldLTY** [comment] 2024-08-29 22:23
Since there are no futhre replies for one week, I will close it. Thanks a lot.

**Closed as completed by HelloWorldLTY** 2024-08-29 22:23 UTC
